## Part A  – Dataset Understanding & Motivation 


* ### What the dataset represents (domain, context): 
    *   This dataset consists of four CSV files in the domain of global education and human development.It tracks the amount of education people receive in various countries and, in some files, how that education translates into actual learning through learning-adjusted years of schooling. The files collectively span several decades and numerous nations or areas, making it possible to analyze long-term trends like the growth of basic education, shifts in gender gaps, and distinctions between low- and high-income nations.
* ### Why it is interesting or useful: 
    * Because education has a significant impact on social mobility, health outcomes, and economic growth, monitoring these metrics over time aids in assessing a nation's progress and inequality. It is possible to examine how variables like enrollment, learning-adjusted years, and education spending move together, revealing patterns of advancement and stagnation across regions and income groups, thanks to the availability of multiple indicators per country-year. Since the data is split into four related tables, combining on shared keys such as country and year allows for a more comprehensive analysis leading to more insightful patterns than one table alone.
* ### Potential real-world or ML applications: 
    * In practice, this dataset can help with descriptive policy analysis by, for instance, identifying areas where learning and schooling outcomes fall short and measuring educational gaps based on gender or income. It can also be used for machine learning tasks like modeling how changes in spending or student-teacher ratios may impact future education outcomes, clustering countries into similar education profiles, and predicting learning-adjusted years of schooling from economic and demographic indicators.
* ### A link to the dataset source: 
    https://www.kaggle.com/datasets/imtkaggleteam/global-education

## Part B – Data Preprocessing & Cleaning

### Inspecting the data of the four tables before merging them

In [21]:
import pandas as pd

basic_education = pd.read_csv("archive/1- share-of-the-world-population-with-at-least-basic-education.csv")
learning_years = pd.read_csv("archive/2- learning-adjusted-years-of-school-lays.csv")
out_school = pd.read_csv("archive/3- number-of-out-of-school-children.csv")
gap = pd.read_csv("archive/4- gender-gap-education-levels.csv")

basic_education.info() 
learning_years.info()
gap.info() # Check the structure of the gap dataset, automatically prints the number of rows, columns, and data types of each column
out_school.info() #doesnot need display() or print() because info() already prints the output to the console

display(basic_education.head()) 
display(basic_education.tail())
display(learning_years.head())
display(learning_years.tail())
display(out_school.head())
display(out_school.tail())
display(gap.head()) # displays prints the data in a more readable format than print() and allows for better formatting of the output, such as showing the first few rows of a DataFrame in a tabular format
display(gap.tail()) # it only works with ipynb



display(basic_education.shape, basic_education.columns) # gap.shape => (entries, columns) gap.columns => list of column names in gap
display(learning_years.shape, learning_years.columns)
display(out_school.shape, out_school.columns)
display(gap.shape, gap.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 468 entries, 0 to 467
Data columns (total 5 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   Entity                                                     468 non-null    object
 1   Code                                                       350 non-null    object
 2   Year                                                       468 non-null    int64
 3   Share of population with no formal education, 1820-2020    468 non-null    float64
 4   Share of population with some formal education, 1820-2020  468 non-null    float64
dtypes: float64(2), int64(1), object(2)
memory usage: 18.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 637 entries, 0 to 636
Data columns (total 4 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Entity                             637 non-null    object
 1   Code                               601 non-null    object
 2   Year                               637 non-null    int64
 3   Learning-Adjusted Years of School  637 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 20.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9228 entries, 0 to 9227
Data columns (total 9 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   Entity                                                         9228 non-null   object
 1   Code                                                           8562 non-null   object
 2   Year                                                           9228 non-null   int64
 3   Combined gross enrolment ratio for tertiary education, female  8251 non-null   float64
 4   Combined gross enrolment ratio for tertiary education, male    8251 non-null   float64
 5   Combined total net enrolment rate, secondary, male             6538 non-null   float64
 6   Combined total net enrolment rate, secondary, female           6538 non-null   float64
 7   Combined total net enrolment rate, primary, female             6855 non-null   float64
 8   Combined total net enrolment rate, primary, male               6855 non-null   float64
dtypes: float64(6), int64(1), object(2)
memory usage: 649.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2580 entries, 0 to 2579
Data columns (total 5 columns):
 #   Column                                                                                              Non-Null Count  Dtype
---  ------                                                                                              --------------  -----
 0   Entity                                                                                              2580 non-null   object
 1   Code                                                                                                2080 non-null   object
 2   Year                                                                                                2580 non-null   int64
 3   Out-of-school children, adolescents and youth of primary and secondary school age, male (number)    2577 non-null   float64
 4   Out-of-school children, adolescents and youth of primary and secondary school age, female (number)  2577 non-null   float64
dtypes: float64(2), int64(1), object(2)
memory usage: 100.9+ KB

,Entity,Code,Year,"Share of population with no formal education, 1820-2020","Share of population with some formal education, 1820-2020"
0,Albania,ALB,2015,2.0,98.0
1,Albania,ALB,2020,1.0,99.0
2,Algeria,DZA,2015,16.0,84.0
3,Algeria,DZA,2020,13.0,87.0
4,Argentina,ARG,2015,2.0,98.0

,Entity,Code,Year,"Share of population with no formal education, 1820-2020","Share of population with some formal education, 1820-2020"
463,World,OWID_WRL,2020,13.0,87.0
464,Zambia,ZMB,2015,6.0,94.0
465,Zambia,ZMB,2020,5.0,95.0
466,Zimbabwe,ZWE,2015,4.0,96.0
467,Zimbabwe,ZWE,2020,3.0,97.0

        Entity Code  Year  Learning-Adjusted Years of School
0  Afghanistan  AFG  2017                           4.870000
1  Afghanistan  AFG  2018                           4.949788
2  Afghanistan  AFG  2020                           5.052838
3       Africa  NaN  2017                           4.931378
4       Africa  NaN  2018                           5.123904

       Entity Code  Year  Learning-Adjusted Years of School
632    Zambia  ZMB  2020                           5.036293
633  Zimbabwe  ZWE  2010                           6.835774
634  Zimbabwe  ZWE  2017                           6.350000
635  Zimbabwe  ZWE  2018                           7.006610
636  Zimbabwe  ZWE  2020                           7.006610

,Entity,Code,Year,"Out-of-school children, adolescents and youth of primary and secondary school age, male (number)","Out-of-school children, adolescents and youth of primary and secondary school age, female (number)"
0,Albania,ALB,2000,78614.0,81341.0
1,Albania,ALB,2001,77837.0,78849.0
2,Albania,ALB,2013,27879.0,21727.0
3,Albania,ALB,2014,21542.0,16571.0
4,Albania,ALB,2015,18407.0,13250.0

,Entity,Code,Year,"Out-of-school children, adolescents and youth of primary and secondary school age, male (number)","Out-of-school children, adolescents and youth of primary and secondary school age, female (number)"
2575,Zimbabwe,ZWE,2001,386981.0,474012.0
2576,Zimbabwe,ZWE,2002,462514.0,550123.0
2577,Zimbabwe,ZWE,2003,522317.0,600606.0
2578,Zimbabwe,ZWE,2012,284958.0,333954.0
2579,Zimbabwe,ZWE,2013,277406.0,320425.0

,Entity,Code,Year,"Combined gross enrolment ratio for tertiary education, female","Combined gross enrolment ratio for tertiary education, male","Combined total net enrolment rate, secondary, male","Combined total net enrolment rate, secondary, female","Combined total net enrolment rate, primary, female","Combined total net enrolment rate, primary, male"
0,Afghanistan,AFG,1986,0.62182,3.60227,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,1990,1.40606,2.96306,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,2003,0.51657,1.82170,NaN,NaN,NaN,NaN
3,Afghanistan,AFG,2004,0.51396,1.82145,NaN,NaN,NaN,NaN
4,Afghanistan,AFG,2009,1.41213,5.97378,NaN,NaN,NaN,NaN

,Entity,Code,Year,"Combined gross enrolment ratio for tertiary education, female","Combined gross enrolment ratio for tertiary education, male","Combined total net enrolment rate, secondary, male","Combined total net enrolment rate, secondary, female","Combined total net enrolment rate, primary, female","Combined total net enrolment rate, primary, male"
9223,Zimbabwe,ZWE,2000,NaN,NaN,44.75129,40.17528,89.00224,88.52073
9224,Zimbabwe,ZWE,2001,NaN,NaN,45.72983,40.98154,92.54698,91.74628
9225,Zimbabwe,ZWE,2002,NaN,NaN,43.78683,38.72148,89.90188,89.31955
9226,Zimbabwe,ZWE,2003,NaN,NaN,39.19233,35.34257,89.42919,88.45444
9227,Zimbabwe,ZWE,1998,NaN,NaN,NaN,NaN,85.61508,83.42723

(468, 5)

Index(['Entity', 'Code', 'Year',
       'Share of population with no formal education, 1820-2020',
       'Share of population with some formal education, 1820-2020'],
      dtype='object')

(637, 4)

Index(['Entity', 'Code', 'Year', 'Learning-Adjusted Years of School'], dtype='object')

(2580, 5)

Index(['Entity', 'Code', 'Year',
       'Out-of-school children, adolescents and youth of primary and secondary school age, male (number)',
       'Out-of-school children, adolescents and youth of primary and secondary school age, female (number)'],
      dtype='object')

(9228, 9)

Index(['Entity', 'Code', 'Year',
       'Combined gross enrolment ratio for tertiary education, female',
       'Combined gross enrolment ratio for tertiary education, male',
       'Combined total net enrolment rate, secondary, male',
       'Combined total net enrolment rate, secondary, female',
       'Combined total net enrolment rate, primary, female',
       'Combined total net enrolment rate, primary, male'],
      dtype='object')

### Merging The four tables together

In [23]:
# MERGE EXPLANATION:
# .merge() combines two DataFrames based on common columns (Entity, Year, Code)
# - When a match is found (same Entity+Year+Code in both tables): combines rows horizontally, 
#   keeping the common columns once and adding all feature columns from both tables
# - When no match: behavior depends on 'how' parameter
#
# how='inner': Only keeps rows that exist in BOTH tables (strictest, smallest dataset, minimal NaN)
# how='outer': Keeps ALL rows from both tables (largest dataset, adds NaN for missing data)
# how='left':  Keeps ALL rows from left (first) table, only matching rows from right (second) table
#
# Suffixes handle duplicate column names when merging.
# When both tables have a column with the same name (besides the merge keys like Entity, Year, Code), pandas adds suffixes to distinguish them.

combined = basic_education.merge(gap, on=['Entity', 'Year', 'Code'], how='outer', suffixes=('_basic', '_gap'))
combined = combined.merge(out_school, on=['Entity', 'Year', 'Code'], how='outer', suffixes=('', '_out'))
combined = combined.merge(learning_years, on=['Entity', 'Year', 'Code'], how='outer', suffixes=('', '_learn'))


display(combined.shape)
print("Missing values per column:")
print(combined.isnull().sum())
display(combined.head())
display(combined.tail())
display(combined.columns)

(9945, 14)

Missing values per column:
Entity                                                                                                   0
Code                                                                                                  1092
Year                                                                                                     0
Share of population with no formal education, 1820-2020                                               9477
Share of population with some formal education, 1820-2020                                             9477
Combined gross enrolment ratio for tertiary education, female                                         1694
Combined gross enrolment ratio for tertiary education, male                                           1694
Combined total net enrolment rate, secondary, male                                                    3407
Combined total net enrolment rate, secondary, female                                                  3407
Combined total net enrolment rate, primary, female                                                    3090
Combined total net enrolment rate, primary, male                                                      3090
Out-of-school children, adolescents and youth of primary and secondary school age, male (number)      7368
Out-of-school children, adolescents and youth of primary and secondary school age, female (number)    7368
Learning-Adjusted Years of School                                                                     9308
dtype: int64

,Entity,Code,Year,"Share of population with no formal education, 1820-2020","Share of population with some formal education, 1820-2020","Combined gross enrolment ratio for tertiary education, female","Combined gross enrolment ratio for tertiary education, male","Combined total net enrolment rate, secondary, male","Combined total net enrolment rate, secondary, female","Combined total net enrolment rate, primary, female","Combined total net enrolment rate, primary, male","Out-of-school children, adolescents and youth of primary and secondary school age, male (number)","Out-of-school children, adolescents and youth of primary and secondary school age, female (number)",Learning-Adjusted Years of School
0,Afghanistan,AFG,1820,NaN,NaN,0.0,0.01,0.01,0.0,0.0,0.01,NaN,NaN,NaN
1,Afghanistan,AFG,1825,NaN,NaN,0.0,0.01,0.01,0.0,0.0,0.01,NaN,NaN,NaN
2,Afghanistan,AFG,1830,NaN,NaN,0.0,0.01,0.01,0.0,0.0,0.01,NaN,NaN,NaN
3,Afghanistan,AFG,1835,NaN,NaN,0.0,0.01,0.01,0.0,0.0,0.01,NaN,NaN,NaN
4,Afghanistan,AFG,1840,NaN,NaN,0.0,0.01,0.01,0.0,0.0,0.01,NaN,NaN,NaN

,Entity,Code,Year,"Share of population with no formal education, 1820-2020","Share of population with some formal education, 1820-2020","Combined gross enrolment ratio for tertiary education, female","Combined gross enrolment ratio for tertiary education, male","Combined total net enrolment rate, secondary, male","Combined total net enrolment rate, secondary, female","Combined total net enrolment rate, primary, female","Combined total net enrolment rate, primary, male","Out-of-school children, adolescents and youth of primary and secondary school age, male (number)","Out-of-school children, adolescents and youth of primary and secondary school age, female (number)",Learning-Adjusted Years of School
9940,Zimbabwe,ZWE,2015,4.0,96.0,9.17213,10.91966,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9941,Zimbabwe,ZWE,2016,NaN,NaN,8.54473,7.76729,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9942,Zimbabwe,ZWE,2017,NaN,NaN,9.68927,8.00596,NaN,NaN,NaN,NaN,NaN,NaN,6.35000
9943,Zimbabwe,ZWE,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.00661
9944,Zimbabwe,ZWE,2020,3.0,97.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.00661

Index(['Entity', 'Code', 'Year',
       'Share of population with no formal education, 1820-2020',
       'Share of population with some formal education, 1820-2020',
       'Combined gross enrolment ratio for tertiary education, female',
       'Combined gross enrolment ratio for tertiary education, male',
       'Combined total net enrolment rate, secondary, male',
       'Combined total net enrolment rate, secondary, female',
       'Combined total net enrolment rate, primary, female',
       'Combined total net enrolment rate, primary, male',
       'Out-of-school children, adolescents and youth of primary and secondary school age, male (number)',
       'Out-of-school children, adolescents and youth of primary and secondary school age, female (number)',
       'Learning-Adjusted Years of School'],
      dtype='object')

### Computing extra features to match assignment requirements

In [26]:
# positive = more males, negative = more females
combined['tertiary_gender_gap'] = combined['Combined gross enrolment ratio for tertiary education, male'] - combined['Combined gross enrolment ratio for tertiary education, female']
combined['secondary_gender_gap'] = combined['Combined total net enrolment rate, secondary, male'] - combined['Combined total net enrolment rate, secondary, female']
combined['primary_gender_gap'] = combined['Combined total net enrolment rate, primary, male'] - combined['Combined total net enrolment rate, primary, female']

# total out of school
combined['total_out_of_school'] = combined['Out-of-school children, adolescents and youth of primary and secondary school age, male (number)'] + combined['Out-of-school children, adolescents and youth of primary and secondary school age, female (number)']

# Total tertiary enrollment
combined['total_tertiary_enrollment'] = combined['Combined gross enrolment ratio for tertiary education, male'] + combined['Combined gross enrolment ratio for tertiary education, female']

# Decade
combined['decade'] = (combined['Year'] // 10) * 10

# Check the updated dataset
display(combined.shape)

(9945, 20)